### ISSUE TITLE
report enanchement

### ISSUE THREAD

**Issue by 42andeverything** [OmniNecs/Maximo#1]
- highlighting of standard tables  in **Data Volume** 
- into Sites `**Breakdown**
       -  merge columns POs and POs Line
       - add columns SR, job plan, inventory transactions, active workflow process?

**Comment by bportaluri** [comment]
Cannot highlight standard/custom tables in the data volume report because stats are retrived fromdatabase system tables.
Other improvements implemented in 0e7148ff9d375ad7de1560521f1c3ba6a842437f
